### ISSUE TITLE
Blob/File Streams

### ISSUE THREAD

**Issue by jeslie0** [purescript-web/purescript-web-file#23]
Hello,
I noticed that the ability to create a stream from a blob or file is missing from this repository. Is there a particular reason why it wasn't included, or is that beyond the scope of this package?

**Comment by garyb** [comment]
I think this library was introduced before [`purescript-web-streams`](https://github.com/purescript-web/purescript-web-streams) so it was omitted due to that - with the web APIs there's so much to cover that they're sometimes lazily implemented, where trickier things are left out until they're needed by someone :wink:

**Comment by jeslie0** [comment]
Ah, okay. I am more than happy to help contribute when I have some time. I feel like this repository is the place for wrapping File and Blob streams, rather than [purescript-web-streams](https://github.com/purescript-web/purescript-web-streams) - that looks like a lower level library?

**Comment by garyb** [comment]
Both of them are low level libraries really, everything in the `purescript-web` organisation is just intended to implement the W3C/WHATWG specs without much opinion, so that there's a common ground for interoperability and people can build more expressive libraries on top (although, to be honest, that hasn't seemed to happen much and people just use the low level stuff directly - which is fine, it just lacks some finesse in terms of ergonomics).

What's the kind of thing you were expecting to find? It sounds like it might be a bit more than just having the `stream` accessor for `Blob`.

**Comment by jeslie0** [comment]
My overall goal is to upload a file and plot data about the bytes on the canvas. This can be done on a chunk-by-chunk basis, which also means that the user doesn't have to wait for the whole file to be uploaded before data starts appearing on the canvas, hence a stream makes sense for this use case. 

I was hoping to find a function of type similar to `File -> (Blob -> Aff Unit) -> Aff Unit` that would apply the given function to each chunk.

**Comment by jeslie0** [comment]
I have made a small module that gives streaming functionality to `File`s. I am not sure if it really belongs in this repository though, since it does depend on `purescript-web-streams`. If adding that as a dependency is okay, I am happy to put in a PR here with the code. Otherwise, I think we can close this issue.

**Comment by garyb** [comment]
I think this library is missing something, as there should at least be a `stream` accessor for `Blob` (which would indeed incur the dependency on `web-streams`), but if you've implemented something like the `File -> (Blob -> Aff Unit) -> Aff Unit` you mentioned then yeah it probably is a bit too "opinionated" for what this is intended as. Might be good to publish it as a standalone library of your own though, as it does sound useful!

**Comment by jeslie0** [comment]
The core of what I have is a function:

`read :: forall a. Reader File -> ({done :: Boolean, value :: Uint8Array} -> Effect a) -> Aff a
`

which will output the JavaScript code:

`reader.read().then(chunk => callback(chunk)())`.

That is low level enough for me and is lower than what I had suggested previously, but still might be too high for this library.
